version: '3.8'

services:
  app1:
    image: minsokuri/tranner
    container_name: tranner1
    ports:
      - "8081:8080"  # 내부 포트는 동일하나 외부 포트는 다르게 설정
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRETKEY: ${JWT_SECRETKEY}
    restart: always
    networks:
      - backend

  app2:
    image: minsokuri/tranner
    container_name: tranner2
    ports:
      - "8082:8080"  # 다른 컨테이너의 포트도 다르게 설정
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRETKEY: ${JWT_SECRETKEY}
    restart: always
    networks:
      - backend

  nginx:
    image: nginx
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - backend

networks:
  backend:
    driver: bridge
