version: '3.8'

services:
  app1:
    image: minsokuri/tranner
    container_name: tranner1
    ports:
      - "8081:8080"  # 내부 포트는 동일하나 외부 포트는 다르게 설정
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRETKEY: ${JWT_SECRETKEY}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URL: ${KAKAO_REDIRECT_URL}
    restart: always
    networks:
      - backend

  app2:
    image: minsokuri/tranner
    container_name: tranner2
    ports:
      - "8082:8080"  # 다른 컨테이너의 포트도 다르게 설정
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRETKEY: ${JWT_SECRETKEY}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URL: ${KAKAO_REDIRECT_URL}
    restart: always
    networks:
      - backend

  nginx:
    image: nginx
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트 매핑 추가
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/api.tranner.com:/etc/letsencrypt/live/api.tranner.com:ro
      - /etc/letsencrypt/archive/api.tranner.com:/etc/letsencrypt/archive/api.tranner.com:ro
      - /etc/letsencrypt/keys:/etc/letsencrypt/keys:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend

networks:
  backend:
    driver: bridge
