version: '3.8'

services:
  app:
    image: minsokuri/tranner
    container_name: tranner
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRETKEY: ${JWT_SECRETKEY}
    restart: always
    networks:
      - backend

  nginx:
    image: nginx
    container_name: my_nginx
    ports:
      - "8081:80"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf # 절대 경로로 변경
    depends_on:
      - app
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

