spring:
  config:
    import: optional:application-secret.properties
  application:
    name: capstone
  jwt:
    secret: ${JWT_SECRETKEY}
  profiles:
    active: db

  mail:
    host: smtp.gmail.com
    port: 587
    username: alsdn5737@gmail.com
    password: wrll hejc efxj cyqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  redis:
    host: localhost
    port: 6379
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms