spring:
  server:
    address: 0.0.0.0
    port: 8443
    ssl:
      key-store: classpath:keystore.p12
      key-store-password: traveler2024
      key-store-type: PKCS12
      key-alias: tomcat
      enabled-protocols: TLSv1.2,TLSv1.3
  config:
    import: optional:application-secret.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: false
        use_sql_comments: false
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 30
    hibernate:
      ddl-auto: update
    open-in-view: false
    show_sql: true
  logging:
    level:
      org.hibernate: INFO
