spring:
  config:
    import: optional:application-secret.properties
  application:
    name: capstone
  jwt:
    secret: 231001941d10ebcc4fa9e68707c07752e576b289e6396834e968034d7656a8b8
  profiles:
    active: db

  mail:
    host: smtp.gmail.com
    port: 587
    username: alsdn5737@gmail.com
    password: wrll hejc efxj cyqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  port: 8080
  ssl:
    enabled: false