spring:
  config:
    import: optional:application-secret.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://trannerdb.c3u62yckebm3.ap-northeast-2.rds.amazonaws.com:3306/tranner?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: traveler2024
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update  # 설정해야 테이블 자동 업데이트
    open-in-view: false
    show_sql: true
  logging:
      level:
        org.hibernate: DEBUG
