spring:
  application:
    name: capstone

  datasource:
    url: jdbc:h2:mem:test  # H2 메모리 데이터베이스
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update  # 기존 데이터를 유지하고, 필요시 create로 변경 가능
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console  # H2 콘솔 경로 설정

server:
  port: 8080  # 서버 포트 설정
